In [1]:
from tqdm.notebook import tqdm
for i in tqdm(range(100)):
    pass

  0%|          | 0/100 [00:00<?, ?it/s]

In [31]:
import numpy as np

In [2]:
import mlflow

In [3]:

mlflow.set_tracking_uri("http://mlflow:5000")
mlflow.set_experiment("gingo")

2026/03/27 23:46:47 INFO mlflow.tracking.fluent: Experiment with name 'exp1' does not exist. Creating a new experiment.

In [3]:
import polars as pl
data_pl = pl.read_csv(r"../data/train.csv",encoding="shift_jis")

In [4]:
data_new = data_pl.with_columns(
    pl.col("含水率").log().alias("含水率_log")
)

In [5]:
data_new.head(1)

shape: (1, 1_560)
┌────────┬────────────┬──────────┬────────────┬───┬───────────┬───────────┬────────────┬───────────┐
│ sample ┆ species    ┆ 樹種     ┆ 含水率     ┆ … ┆ 4007.5356 ┆ 4003.6785 ┆ 3999.82139 ┆ 含水率_lo │
│ number ┆ number     ┆ ---      ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---        ┆ g         │
│ ---    ┆ ---        ┆ str      ┆ f64        ┆   ┆ f64       ┆ f64       ┆ f64        ┆ ---       │
│ i64    ┆ i64        ┆          ┆            ┆   ┆           ┆           ┆            ┆ f64       │
╞════════╪════════════╪══════════╪════════════╪═══╪═══════════╪═══════════╪════════════╪═══════════╡
│ 1      ┆ 1          ┆ イチョウ ┆ 216.129032 ┆ … ┆ 1.23087   ┆ 1.23354   ┆ 1.23219    ┆ 5.375876  │
└────────┴────────────┴──────────┴────────────┴───┴───────────┴───────────┴────────────┴───────────┘

In [6]:
import polars as pl
import numpy as np
import mlflow
import mlflow.lightgbm
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# ===== MLflow設定 =====
mlflow.set_tracking_uri("http://mlflow:5000")
mlflow.set_experiment("gingo")

# ===== データ =====
pl_df = data_new 

# 目的変数
y = pl_df["含水率_log"].to_numpy()

# 不要列除外
drop_cols = ["含水率", "含水率_log", "樹種", "sample number", "species number"]

X = pl_df.drop(drop_cols).to_numpy()

# ===== 分割 =====
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ===== 学習 =====
params = {
    "n_estimators": 500,
    "learning_rate": 0.05,
    "num_leaves": 64,
    "min_data_in_leaf": 5,
    "n_jobs": -1
}

with mlflow.start_run():

    # パラメータ記録
    mlflow.log_params(params)

    model = LGBMRegressor(**params)
    model.fit(X_train, y_train)

    # 予測
    pred = model.predict(X_valid)

    # RMSE（squared=False使えない環境対応）
    rmse = np.sqrt(mean_squared_error(y_valid, pred))

    # ログ
    mlflow.log_metric("rmse", rmse)

    # モデル保存
    mlflow.lightgbm.log_model(model, "model")

    print("RMSE:", rmse)

[LightGBM] [Warning] min_data_in_leaf is set=5, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=5
[LightGBM] [Warning] min_data_in_leaf is set=5, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.027973 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 396525
[LightGBM] [Info] Number of data points in the train set: 1057, number of used features: 1555
[LightGBM] [Info] Start training from score 3.408297

/usr/local/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
2026/03/28 00:06:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

[LightGBM] [Warning] min_data_in_leaf is set=5, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=5

2026/03/28 00:06:39 WARNING mlflow.lightgbm: Saving the models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

RMSE: 0.18669948455892013
🏃 View run entertaining-cub-868 at: http://mlflow:5000/#/experiments/1/runs/0b6458984058453b94948314bb0a87ed
🧪 View experiment at: http://mlflow:5000/#/experiments/1

In [12]:
!head ../data/sample_submit.csv

95,50
96,50
97,50
98,50
99,50
100,50
101,50
102,50
103,50
104,50

In [15]:
import mlflow

mlflow.set_tracking_uri("http://mlflow:5000")

# exp1のrun取得
runs = mlflow.search_runs(experiment_names=["exp1"])

# RMSE最小のrunを使う
best_run = runs.sort_values("metrics.rmse").iloc[0]
run_id = best_run["run_id"]

# モデルロード
model = mlflow.lightgbm.load_model(f"runs:/{run_id}/model")

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

In [18]:
!ls ../data/test.csv

test_data =  pl.read_csv(r"../data/test.csv",encoding="shift_jis")

../data/test.csv

In [20]:
test_data.head()

shape: (5, 1_558)
┌────────┬────────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample ┆ species    ┆ 樹種     ┆ 9993.76781 ┆ … ┆ 4011.39271 ┆ 4007.5356 ┆ 4003.6785 ┆ 3999.8213 │
│ number ┆ number     ┆ ---      ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ 9         │
│ ---    ┆ ---        ┆ str      ┆ f64        ┆   ┆ f64        ┆ f64       ┆ f64       ┆ ---       │
│ i64    ┆ i64        ┆          ┆            ┆   ┆            ┆           ┆           ┆ f64       │
╞════════╪════════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 95     ┆ 2          ┆ クスノキ ┆ 0.32877    ┆ … ┆ 1.36074    ┆ 1.35224   ┆ 1.33495   ┆ 1.32482   │
│ 96     ┆ 2          ┆ クスノキ ┆ 0.30061    ┆ … ┆ 1.12671    ┆ 1.13182   ┆ 1.1307    ┆ 1.12377   │
│ 97     ┆ 2          ┆ クスノキ ┆ 0.26048    ┆ … ┆ 0.99367    ┆ 0.98723   ┆ 0.98868   ┆ 0.99461   │
│ 98     ┆ 2          ┆ クスノキ ┆ 0.2321     ┆ … ┆ 0.95703    ┆ 0.9553    ┆ 0.95444   ┆ 0.95832   │
│ 99     ┆ 2          ┆ クスノキ ┆ 0.19725    ┆ … ┆ 0.90292    ┆ 0.90119   ┆ 0.89835   ┆ 0.89623   │
└────────┴────────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [21]:

pl_test = test_data

drop_cols = ["含水率", "含水率_log", "樹種", "sample number", "species number"]

X_test = pl_test.drop(drop_cols, strict=False).to_numpy()

In [29]:
y_pred_log = model.predict(X_test)

/usr/local/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [32]:
import pandas as pd

y_pred = np.exp(y_pred_log)

submission = pd.DataFrame({
    "id": pl_test["sample number"].to_numpy(),
    "含水率log": y_pred
})

submission.head()

   id      含水率log
0  95  155.217350
1  96  142.366065
2  97  139.324560
3  98  170.698454
4  99  158.247433

In [47]:
submission.to_csv(r"../data/submission.csv",index=False,header = False)

In [48]:
!head ../data/sample_submit.csv

95,50
96,50
97,50
98,50
99,50
100,50
101,50
102,50
103,50
104,50

In [49]:
!head ../data/submission.csv

95,155.21734950644017
96,142.36606481752068
97,139.32455958367885
98,170.69845412595623
99,158.2474328520994
100,133.35389637964118
101,121.29102172161932
102,138.55922050521977
103,162.21300927161576
104,143.97672793012214