In [1]:
from tqdm.notebook import tqdm
for i in tqdm(range(100)):
    pass

  0%|          | 0/100 [00:00<?, ?it/s]

In [31]:
import numpy as np

In [2]:
import mlflow

In [3]:

mlflow.set_tracking_uri("http://mlflow:5000")
mlflow.set_experiment("gingo")

2026/03/27 23:46:47 INFO mlflow.tracking.fluent: Experiment with name 'exp1' does not exist. Creating a new experiment.

In [3]:
import polars as pl
data_pl = pl.read_csv(r"../data/train.csv",encoding="shift_jis")

### 前処理ゾーン

In [4]:
# 含水率をlogにして計算しやすくする

data_new = data_pl.with_columns(
    pl.col("含水率").log().alias("含水率_log")
)

In [52]:
#各カラムの差分をとる

exclude_cols = ["sample number", "species number", 
                "樹種", "含水率", "含水率_log"]
num_cols = [c for c in data_new.columns if c not in exclude_cols]

# 横方向の差分カラム名を作成
diff_cols = [f"{num_cols[i]}_diff_{num_cols[i+1]}"
             for i in range(len(num_cols)-1)]

# 横方向の差分を計算して新規カラムとして追加
diff_exprs = [
    (pl.col(num_cols[i+1]) - pl.col(num_cols[i])).alias(diff_cols[i])
    for i in range(len(num_cols)-1)
]

pl_diff_df = data_new.with_columns(diff_exprs)

In [53]:
#varが0/極端に小さい　ものを排除


# 数値列のみ対象
num_cols = [c for c, d in zip(pl_diff_df.columns, pl_diff_df.dtypes) if d in (pl.Float64, pl.Int64)]

# 分散チェックして残す列
valid_cols = [
    c for c in num_cols
    if pl_diff_df.select(pl.col(c).var()).item() != 0
]

# 元の非数値列も残す
other_cols = [c for c in pl_diff_df.columns if c not in num_cols]

# 結合
pl_diff_df_var = pl_diff_df.select(other_cols + valid_cols)

In [84]:
feature_cols = pl_diff_df_var.drop(drop_cols).columns

In [86]:
#show  feature_cols

In [62]:
import polars as pl
import numpy as np
import mlflow
import mlflow.lightgbm
from lightgbm import LGBMRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# ===== MLflow設定 =====
mlflow.set_tracking_uri("http://mlflow:5000")
mlflow.set_experiment("gingo")

# ===== データ =====
pl_df = pl_diff_df_var 

# 目的変数
y = pl_df["含水率_log"].to_numpy()

# 不要列除外
drop_cols = ["含水率", "含水率_log", "樹種", "sample number", "species number"]

X = pl_df.drop(drop_cols).to_numpy()

# ===== 分割 =====
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ===== 学習 =====
params = {
    "n_estimators": 500,
    "learning_rate": 0.05,
    "num_leaves": 64,
    "min_data_in_leaf": 5,
    "n_jobs": -1
}

with mlflow.start_run():

    # パラメータ記録
    mlflow.log_params(params)

    model = LGBMRegressor(**params)
    model.fit(X_train, y_train)

    # 予測
    pred = model.predict(X_valid)

    # RMSE（squared=False使えない環境対応）
    rmse = np.sqrt(mean_squared_error(y_valid, pred))

    # ログ
    mlflow.log_metric("rmse", rmse)

    # モデル保存
    mlflow.lightgbm.log_model(model, "model")

    print("RMSE:", rmse)

[LightGBM] [Warning] min_data_in_leaf is set=5, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=5
[LightGBM] [Warning] min_data_in_leaf is set=5, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=5
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.226674 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 707985
[LightGBM] [Info] Number of data points in the train set: 1057, number of used features: 3109
[LightGBM] [Info] Start training from score 3.408297

/usr/local/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
2026/03/28 22:32:23 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

[LightGBM] [Warning] min_data_in_leaf is set=5, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=5

2026/03/28 22:32:23 WARNING mlflow.lightgbm: Saving the models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

RMSE: 0.100740808419849
🏃 View run calm-bat-566 at: http://mlflow:5000/#/experiments/2/runs/a311f1f89ab742a4aaf882c042db040e
🧪 View experiment at: http://mlflow:5000/#/experiments/2

In [64]:
import mlflow

mlflow.set_tracking_uri("http://mlflow:5000")

# exp1のrun取得
runs = mlflow.search_runs(experiment_names=["gingo"])

# RMSE最小のrunを使う
best_run = runs.sort_values("metrics.rmse").iloc[0]
run_id = best_run["run_id"]

# モデルロード
model = mlflow.lightgbm.load_model(f"runs:/{run_id}/model")

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

In [73]:
!ls ../data/test.csv

test_data =  pl.read_csv(r"../data/test.csv",encoding="shift_jis")

../data/test.csv

In [76]:
test_data.head(2)

shape: (2, 1_558)
┌────────┬────────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ sample ┆ species    ┆ 樹種     ┆ 9993.76781 ┆ … ┆ 4011.39271 ┆ 4007.5356 ┆ 4003.6785 ┆ 3999.8213 │
│ number ┆ number     ┆ ---      ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ 9         │
│ ---    ┆ ---        ┆ str      ┆ f64        ┆   ┆ f64        ┆ f64       ┆ f64       ┆ ---       │
│ i64    ┆ i64        ┆          ┆            ┆   ┆            ┆           ┆           ┆ f64       │
╞════════╪════════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 95     ┆ 2          ┆ クスノキ ┆ 0.32877    ┆ … ┆ 1.36074    ┆ 1.35224   ┆ 1.33495   ┆ 1.32482   │
│ 96     ┆ 2          ┆ クスノキ ┆ 0.30061    ┆ … ┆ 1.12671    ┆ 1.13182   ┆ 1.1307    ┆ 1.12377   │
└────────┴────────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

### 前処理ゾーン

In [89]:
#各カラムの差分をとる

exclude_cols = ["sample number", "species number", 
                "樹種", "含水率", "含水率_log"]

num_cols = [c for c in test_data.columns if c not in exclude_cols]

# 横方向の差分カラム名を作成
diff_cols = [f"{num_cols[i]}_diff_{num_cols[i+1]}"
             for i in range(len(num_cols)-1)]

# 横方向の差分を計算して新規カラムとして追加
diff_exprs = [
    (pl.col(num_cols[i+1]) - pl.col(num_cols[i])).alias(diff_cols[i])
    for i in range(len(num_cols)-1)
]

test_pl_diff_df = test_data.with_columns(diff_exprs)

In [90]:
#del

pl_diff_df_var.head(2)

shape: (2, 3_114)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ 樹種     ┆ sample ┆ species    ┆ 含水率     ┆ … ┆ 4015.24982 ┆ 4011.3927 ┆ 4007.5356 ┆ 4003.6785 │
│ ---      ┆ number ┆ number     ┆ ---        ┆   ┆ _diff_4011 ┆ 1_diff_40 ┆ _diff_400 ┆ _diff_399 │
│ str      ┆ ---    ┆ ---        ┆ f64        ┆   ┆ .39271     ┆ 07.5356   ┆ 3.6785    ┆ 9.82139   │
│          ┆ i64    ┆ i64        ┆            ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆            ┆            ┆   ┆ f64        ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ イチョウ ┆ 1      ┆ 1          ┆ 216.129032 ┆ … ┆ -0.00163   ┆ 0.00269   ┆ 0.00267   ┆ -0.00135  │
│ イチョウ ┆ 2      ┆ 1          ┆ 210.752688 ┆ … ┆ -0.00131   ┆ 0.00434   ┆ 0.00393   ┆ -0.00055  │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [92]:
#del

X_test = test_pl_diff_df.select(feature_cols).to_numpy()

In [93]:
#del
X_test

array([[ 0.32877,  0.32855,  0.32823, ..., -0.0085 , -0.01729, -0.01013],
       [ 0.30061,  0.30006,  0.29978, ...,  0.00511, -0.00112, -0.00693],
       [ 0.26048,  0.26033,  0.26   , ..., -0.00644,  0.00145,  0.00593],
       ...,
       [-0.08285, -0.08289, -0.08286, ..., -0.00209, -0.00102, -0.0013 ],
       [-0.08265, -0.08257, -0.08252, ..., -0.00315, -0.00202, -0.00153],
       [-0.0822 , -0.08223, -0.08221, ..., -0.00043, -0.00287, -0.00537]],
      shape=(550, 3109))

### 予測ゾーン

In [94]:
y_pred_log = model.predict(X_test)

[LightGBM] [Warning] min_data_in_leaf is set=5, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=5

/usr/local/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [95]:
import pandas as pd

y_pred = np.exp(y_pred_log)

submission = pd.DataFrame({
    "id": pl_test["sample number"].to_numpy(),
    "含水率log": y_pred
})

submission.head()

   id      含水率log
0  95  166.113378
1  96  166.651277
2  97  153.954212
3  98  137.396828
4  99  178.414332

In [96]:
submission.to_csv(r"../data/submission.csv",index=False,header = False)

In [97]:
!head ../data/sample_submit.csv

95,50
96,50
97,50
98,50
99,50
100,50
101,50
102,50
103,50
104,50

In [98]:
!head ../data/submission.csv

95,166.11337781799068
96,166.6512773308302
97,153.95421196044404
98,137.396828066121
99,178.41433178232276
100,170.5195446541208
101,155.21145474892003
102,144.03780953678992
103,163.8153437957844
104,140.7844741250766